---
name: Kernel

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  kernel:
    name: Kernel
    runs-on: ubuntu-22.04
    container: i73v/nos-build-machine:latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          task kernel:setup BUILD_TYPE=${{ matrix.build-type }}

      - name: Compile
        run: |
          task kernel:compile BUILD_TYPE=${{ matrix.build-type }}
