---
name: Native Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  native-unit-tests:
    name: Native Unit Tests
    runs-on: ubuntu-22.04
    container: i73v/nos-build-machine:latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          task native:setup BUILD_TYPE=${{ matrix.build-type }}

      - name: Compile - libncxx
        run: |
          task native:compile BUILD_TYPE=${{ matrix.build-type }} -- libncxx

      - name: Test - libncxx
        run: |
          task native:test BUILD_TYPE=${{ matrix.build-type }} -- libncxx
