---
name: Native Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  native-unit-tests:
    name: Native Unit Tests
    runs-on: ubuntu-22.04
    container: i73v/nos-build-machine:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          task setup:native

      - name: Compile - libncxx
        run: |
          task compile -- libncxx

      - name: Test - libncxx
        run: |
          task test -- libncxx
